[package]
name = "aster-network"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aster-bigtcp.workspace = true
aster-softirq.workspace = true
bitvec.workspace = true
component.workspace = true
ostd.workspace = true
spin.workspace = true

[lints]
workspace = true
