# This file is to help typos avoid false-positives.

# The regexes below are considered valid and should not be flagged as typos.
[default]
extend-ignore-re = [ "sha256 = \"([a-zA-Z0-9]+)\";" ]

# Words listed below are marked as valid, not mistakes. 
[default.extend-words]
rela = "rela"
ANDD = "ANDD"
ethe = "ethe"
mke  = "mke"
WHT  = "WHT"
ist  = "ist"
sie  = "sie"
TME  = "TME"
BA   = "BA"
ND   = "ND"
Fo   = "Fo"
pn   = "pn"
sme  = "sme"
Inh  = "Inh"
DELET = "DELET"
wrk = "wrk"
rto = "rto"
typ = "typ"
sigfault = "sigfault"
sems = "sems"
THRE = "THRE"

# Files with svg suffix are ignored to check. 
[type.svg]
extend-glob = ["*.svg"]
check-file = false

# Files listed below are ignored to check.
[files]
extend-exclude = [
    "test/initramfs/src/syscall/gvisor/blocklists/pty_test",
    "test/initramfs/build/initramfs/opt/gvisor/blocklists/pty_test",
    "test/initramfs/src/syscall/gvisor/blocklists/sync_test",
    "test/initramfs/build/initramfs/opt/gvisor/blocklists/sync_test",
]
