# template
[components]
nix = { name = "aster-nix" }
virtio = { name = "aster-virtio" }
input = { name = "aster-input" }
block = { name = "aster-block" }
console = { name = "aster-console" }
softirq = { name = "aster-softirq" }
time = { name = "aster-time" }
framebuffer = { name = "aster-framebuffer" }
network = { name = "aster-network" }

[whitelist]
[whitelist.nix.main]
main = true
