# template
[components]
block = { name = "aster-block" }
cmdline = { name = "aster-cmdline" }
console = { name = "aster-console" }
framebuffer = { name = "aster-framebuffer" }
i8042 = { name = "aster-i8042" }
input = { name = "aster-input" }
kernel = { name = "aster-kernel" }
logger = { name = "aster-logger" }
mlsdisk = { name = "aster-mlsdisk" }
network = { name = "aster-network" }
pci = { name = "aster-pci" }
softirq = { name = "aster-softirq" }
systree = { name = "aster-systree" }
time = { name = "aster-time" }
uart = { name = "aster-uart" }
virtio = { name = "aster-virtio" }

[whitelist]
[whitelist.nix.main]
main = true
