[package]
name = "osdk-frame-allocator"
description = "The default buddy system frame allocator shipped with OSDK."
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = "0.4"
ostd = { version = "0.17.0", path = "../../../ostd" }
paste = "1.0.15"

[lints]
workspace = true
