[package]
name = "osdk-frame-allocator"
description = "The default buddy system frame allocator shipped with OSDK."
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
ostd.workspace = true
paste.workspace = true

[lints]
workspace = true
