[package]
name = "aster-framebuffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ostd = { path = "../../../ostd" }
component = { path = "../../libs/comp-sys/component" }
aster-console = { path = "../console" }
aster-i8042-controller ={ path = "../../comps/i8042_controller" }


log = "0.4"
spin = "0.9.4"

[lints]
workspace = true
