[package]
name = "aster-time"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aster-util.workspace = true
bitflags.workspace = true
component.workspace = true
log.workspace = true
ostd.workspace = true
spin.workspace = true

[target.riscv64imac-unknown-none-elf.dependencies]
chrono = { version = "0.4.38", default-features = false }

[lints]
workspace = true
