[package]
name = "aster-systree"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aster-util.workspace = true
bitflags = "2.5"
component.workspace = true
inherit-methods-macro.workspace = true
ostd.workspace = true
spin.workspace = true

[lints]
workspace = true
