[package]
name = "osdk-test-kernel"
description = "The OSTD-based kernel for running unit tests with OSDK."
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ostd.workspace = true
owo-colors.workspace = true

[lints]
workspace = true
