[package]
name = "osdk-test-kernel"
description = "The OSTD-based kernel for running unit tests with OSDK."
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ostd = { version = "0.17.0", path = "../../../ostd" }
owo-colors = "4.0.0"

[lints]
workspace = true
