[package]
name = "osdk-heap-allocator"
version = "0.16.0"
edition = "2021"
description = "The default slab-based heap allocator shipped with OSDK."
license = "MPL-2.0"
repository ="https://github.com/asterinas/asterinas"
readme = "README.md"

[dependencies]
log = "0.4"
ostd = { version = "0.16.0", path = "../../../ostd" }

[lints]
workspace = true
