[package]
name = "osdk-heap-allocator"
description = "The default slab-based heap allocator shipped with OSDK."
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = "0.4"
ostd = { version = "0.17.0", path = "../../../ostd" }

[lints]
workspace = true
