name: Check licenses
on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  direct:
    runs-on: ubuntu-latest
    steps:
    - run: df -alh

  in-docker:
    runs-on: ubuntu-latest
    container:
      image: asterinas/asterinas:0.17.0-20251217
      options: -v /dev:/dev -v /mnt:/mnt --privileged
    steps:
    - run: df -alh
