name: Validate SCML files with sctrace

on:
  workflow_dispatch:
  pull_request:
    paths:
      - tools/sctrace/**
      - book/src/kernel/linux-compatibility/syscall-flag-coverage/**
  push:
    branches:
      - main
    paths:
      - tools/sctrace/**
      - book/src/kernel/linux-compatibility/syscall-flag-coverage/**

jobs:
  validate_scmls:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: asterinas/asterinas:0.16.2-20251209
    steps:
      - uses: actions/checkout@v4
      - name: Validate SCML files with sctrace
        run: ./tools/sctrace.sh -- echo "Asterinas"
