[package]
name = "jinux-virtio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
spin = "0.9.4"
jinux-frame = {path = "../../../framework/jinux-frame"}
jinux-pci = {path="../jinux-pci"}
jinux-util = {path="../../libs/jinux-util"}
pod = {path = "../../../framework/pod"}
pod-derive = {path = "../../../framework/pod-derive"}
log= "0.4"


[features]

